# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knapsack_brute_force_cpp <- function(x, W) {
    .Call('Lab6_knapsack_brute_force_cpp', PACKAGE = 'Lab6', x, W)
}

knapsack_dynamic_cpp <- function(x, W) {
    .Call('Lab6_knapsack_dynamic_cpp', PACKAGE = 'Lab6', x, W)
}

knapsack_greedy_cpp <- function(x, W) {
    .Call('Lab6_knapsack_greedy_cpp', PACKAGE = 'Lab6', x, W)
}

