# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knapsack_brute_force_cpp <- function(x, W) {
    .Call('Lab6_knapsack_brute_force_cpp', PACKAGE = 'Lab6', x, W)
}

