#' A Reference Class to represent Ridge regression models.
#'
#' Stores information about a Ridge regression model generated by \code{ridgereg}.
#'
#' @field call Object of class \code{"character"}. A string representation of the calling code.
#' @field coefficients Object of class \code{"list"}. A list containing information about the estimated coefficients.
#' \describe{
#' \item{\code{val}:}{The estimated coefficients.}
#' \item{\code{se}:}{The standard errors of the coefficients.}
#' \item{\code{var}:}{The variance of the coefficients.}
#' \item{\code{tval}:}{The t values of the the coefficients.}
#' \item{\code{pval}:}{The p values of the coefficients.}
#' }
#' @field fitted.values  The fitted values of y using the model's coefficients.
#' @field df  The number of degrees of freedom in the model.
#'
#' @import methods
#'
#' @aliases ridgeregmod
#' @exportClass RidgeRegressionModel
RidgeRegressionModel <- setRefClass("RidgeRegressionModel",
                                     fields=list(
                                         call="character",
                                         coefficients="list",
                                         fitted.values="numeric",
                                     ))

## Constructor and Destructor
RidgeRegressionModel$methods(list(
                          initialize = function(call, coefficients, fitted.values, ...) {
                              .initialize(.self, call, coefficients, fitted.values, ...)
                              callSuper(...)
                          }
                      ))

## Methods
RidgeRegressionModel$methods(list(
                          coef = function() {
                              "Returns the estimated coefficients."
                              return(coefficients$val)
                          },
                          pred = function() {
                              "Returns the fitted values."
                              return(fitted.values)
                          },
                          summary = function() {
                              "Shows a summary of the model."
                              .summary(.self)
                          },
                          print = function() {
                              "Prints the model."
                              .print(.self)
                          },
                          show = function() {
                              print()
                          }
                     ))
