#' A Reference Class to represent Ridge regression models.
#'
#' Stores information about a Ridge regression model generated by \code{ridgereg}.
#'
#' @field call Object of class \code{"character"}. A string representation of the calling code.
#' @field coefficients Object of class \code{"numeric"}. Contains the coefficients.
#' @field fitted.values  The fitted values of y using the model's coefficients.
#' @field center The values used to center the data.
#' @field scale The values used to scale the data.
#' @field variables The variables used to create the model.
#' @field lambda The lambda parameter, >= 0.
#'
#' @import methods
#'
#' @aliases ridgeregmod
#' @exportClass RidgeRegressionModel
RidgeRegressionModel <- setRefClass("RidgeRegressionModel",
                                     fields=list(
                                         call="character",
                                         coefficients="numeric",
                                         fitted.values="numeric",
                                         center="numeric",
                                         scale="numeric",
                                         variables="character",
                                         lambda="numeric"
                                     ))

## Constructor and Destructor
RidgeRegressionModel$methods(list(
                          initialize = function(call, formula, data, lambda, ...) {
                              .initialize(.self, call, formula, data, lambda, ...)
                              callSuper(...)
                          }
                     ))

## Methods
RidgeRegressionModel$methods(list(
                         coef = function() {
                             "Returns the estimated coefficients."
                             .coef(.self)
                         },
                         pred = function(X=NULL) {
                             "Returns the lastest fitted values or
                               if X is specified it will return new predicted values.
                               X do not need to be scaled, it is performed inside this method."
                             .pred(.self, X)
                         },
                         print = function() {
                             "Prints the model."
                             .print(.self)
                         },
                         show = function() {
                             print()
                         }
                     ))
