#' A Reference Class to represent linear regression models.
#'
#' Stores information about a linear regression model generated by \code{linreg}.
#'
#' @import methods
#' @exportClass LinearRegressionModel
#'
#' @field call Object of class \code{"character"}. A string representation of the calling code.
#' @field coefficients Object of class \code{"list"}. A list containing information about the estimated coefficients.
#' \describe{
#' \item{\code{val}:}{Object of class \code{"numeric"}. The estimated parameters.}
#' \item{\code{se}:}{Object of class \code{"numeric"}. The standard errors of the parameters.}
#' \item{\code{var}:}{Object of class \code{"numeric"}. The variance of the parameters.}
#' \item{\code{tval}:}{Object of class \code{"numeric"}. The t-values of the the parameters.}
#' \item{\code{pval}:}{Object of class \code{"numeric"}. The p-values of the parameters.}
#' }
#' @field residuals Ojbect of class \code{"list"}. A list containing information about the residuals.
#' \describe{
#' \item{\code{val}:}{Object of class \code{"numeric"}. The residuals.}
#' \item{\code{var}:}{Object of class \code{"numeric"}. The variance of the residuals.}
#' }
#' @field fitted.values Object of class \code{"numeric"}. The fitted values of y using the model's parameters.
#' @field df Object of class \code{"numeric"}. The number of degrees of freedom in the model.
#'
#' @name linregmod
#' @source \url{https://en.wikipedia.org/wiki/Linear_regression}
linregmod <- setRefClass("LinearRegressionModel",
                         fields=list(
                             call="character",
                             coefficients="list",
                             residuals="list",
                             fitted.values="numeric",
                             df="numeric"
                         ))


## Constructor and Destructor
linregmod$methods(list(
              initialize = function(call, coefficients, residuals, fitted.values,
                                    df, ...) {
                  ## Extract the string representation of the call
                  call <<- gsub(" +", " ", paste(deparse(call), collapse=""))

                  coefficients <<- coefficients
                  residuals <<- residuals
                  fitted.values <<- fitted.values
                  df <<- df

                  callSuper(...)
              },
              finalize = function() {

              }
          ))

## Generic Functions
linregmod$methods(list(
            coef = function() {
                return(coefficients$val)
            },
            resid = function() {
                return(residuals$val)
            },
            pred = function() {
                return(fitted.values)
            },
            summary = function() {
            },
            print = function() {
                ## Might wanna use strwrap.
                format_number <- function(number, decimals) {
                    formatted <- as.numeric(format(round(number, decimals), nsmall=decimals))
                    names(formatted) <- names(number)
                    return(formatted)
                }

                cat("\nCall:\n")
                cat(call)
                cat("\n\n")
                cat("Coefficients:\n  ")
                base::print(format_number(coef(), 4))
            },
            show = function() {
                print()
            },
            plot = function() {
                readkey <- function() {
                    cat ("Press [enter] to continue")
                    line <- readline()
                }

                base_plot <- function(data, title, xlab, ylab) {
                    return(ggplot(data=data) +
                           ggtitle(title) +
                           xlab(xlab) +
                           ylab(ylab) +
                           theme(plot.title=element_text(hjust=0.5)) +
                           geom_point(aes(x=x, y=y)))
                }

                ## Residuals vs Fitted Plot -------------------
                label.title <- "Residuals vs Fitted"
                label.x <- paste("Fitted values", call, sep="\n")
                label.y <- "Residuals"

                data <- data.frame(x=fitted.values, y=residuals$val)

                res_vs_fit_plot <-  base_plot(data, label.title, label.x, label.y) +
                    geom_hline(yintercept=0, linetype="dotted", color="blue")

                base::print(res_vs_fit_plot)

                ## Wait for user input before continuing
                readkey()

                ## Scale-Location Plot ----------------------
                label.title <- "Scale-Location"
                label.y <- expression(sqrt("Standardized residuals"))

                standardized_residuals <- abs(residuals$val / sd(residuals$val))
                data <- data.frame(x=fitted.values, y=sqrt(standardized_residuals))

                scale_location_plot <- base_plot(data, label.title, label.x, label.y)
                base::print(scale_location_plot)
            }
        ))
