// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// knapsack_brute_force_cpp
Rcpp::List knapsack_brute_force_cpp(const Rcpp::DataFrame& x, unsigned W);
RcppExport SEXP Lab6_knapsack_brute_force_cpp(SEXP xSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(knapsack_brute_force_cpp(x, W));
    return rcpp_result_gen;
END_RCPP
}
// knapsack_dynamic_cpp
Rcpp::List knapsack_dynamic_cpp(const Rcpp::DataFrame& x, unsigned W);
RcppExport SEXP Lab6_knapsack_dynamic_cpp(SEXP xSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(knapsack_dynamic_cpp(x, W));
    return rcpp_result_gen;
END_RCPP
}
// knapsack_greedy_cpp
Rcpp::List knapsack_greedy_cpp(const Rcpp::DataFrame& x, unsigned W);
RcppExport SEXP Lab6_knapsack_greedy_cpp(SEXP xSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(knapsack_greedy_cpp(x, W));
    return rcpp_result_gen;
END_RCPP
}
